sonar.projectName='1ibms-ui-react'
sonar.sourceEncoding=UTF-8
sonar.sources=server/src,client/src
sonar.tests=server/src,client/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info
sonar.verbose=false
sonar.typescript.file.suffixes=.ts,.tsx
sonar.exclusions=server/webpack.config.js,server/jest.env.js,server/live-reload.js,server/src/index.ts,server/src/app.ts,server/src/swagger.ts,**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/*.scss,**/*.css,**/*.html,client/src/App.tsx,client/src/setupTests.ts,client/update-app-config.js,client/jest.config.js,client/webpack.config.production.js,client/webpack.config.development.js
sonar.typescript.tsconfigPath=server/src/tsconfig.json